on:
  workflow_dispatch:
    inputs:
      stake:
        description: 'stake.lido.fi'
        required: true
        type: boolean
      trp:
        description: 'trp.lido.fi'
        required: true
        type: boolean
      solana:
        description: 'solana.lido.fi'
        type: boolean
        required: true
      polygon:
        description: 'polygon.lido.fi'
        type: boolean
        required: true
      operators:
        description: 'operators.lido.fi'
        type: boolean
        required: true
      easytrack:
        description: 'easytrack.lido.fi'
        type: boolean
        required: true
      vote:
        description: 'vote.lido.fi'
        type: boolean
        required: true
          
jobs:
  generate-domain-list-dynamic:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Domain List
        env:
          INPUTS: ${{ toJson(github.event.inputs) }}
        run: |
          domain_list=$(echo $INPUTS | jq -r 'to_entries | map(select(.value == "true") | .key + ".lido.fi") | join(",")')
          if [ -z "$domain_list" ]; then
            echo "No domains are set to true. Failing the job."
            exit 1
          fi
          echo "Dynamic Domain List: $domain_list"
