on:
  workflow_dispatch:
    inputs:
      stake:
        description: 'stake.lido.fi'
        required: true
        type: boolean
      trp:
        description: 'trp.lido.fi'
        required: true
        type: boolean
      solana:
        description: 'solana.lido.fi'
        type: boolean
        required: true
      polygon:
        description: 'polygon.lido.fi'
        type: boolean
        required: true
      operators:
        description: 'operators.lido.fi'
        type: boolean
        required: true
      easytrack:
        description: 'easytrack.lido.fi'
        type: boolean
        required: true
      vote:
        description: 'vote.lido.fi'
        type: boolean
        required: true
          
jobs:
  generate-domain-list-dynamic:
    runs-on: ubuntu-latest
    steps:
      - name: Generate domain list
        env:
          INPUTS: ${{ toJSON(inputs) }}
        run: |
          domains=$(echo $INPUTS | jq -r 'to_entries | map(select(.value == "true") | .key + ".lido.fi") | join(",")')
          if [ -z "$domains" ]; then
            echo "No domains are set to true. Failing the job."
            exit 1
          fi
          echo "domain_list=$domains" >> $GITHUB_ENV

      - name: Lockdown
        run: echo ansible-playbook
          playbooks/lockdown_dummy.yaml
          -e lockdown_domain_list=${{ env.domain_list }}
          # -e lockdown_state=${{ github.event.inputs.state }}
        # working-directory: ansible
